---
name: "Test"
on: # yamllint disable-line rule:truthy
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Test:
    runs-on: "ubuntu-24.04"
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.3'
    - uses: "actions/checkout@v4"
    - run: "sudo apt-get update"
    - run: "sudo apt-get install -y cargo"
    - run: "make -j 4 go"
    - run: "mage test"
